import type {
  AuditLogEntry,
  ContentEnvironment,
  ContentTreeItem,
  DependencyFinding,
  TransferRecord,
} from "./types";

export const environments: ContentEnvironment[] = [
  {
    id: "xm-prod",
    name: "XM Cloud Production",
    project: "North America Sites",
    region: "US West",
    type: "Production",
    status: "Connected",
  },
  {
    id: "xm-stage",
    name: "XM Cloud Staging",
    project: "North America Sites",
    region: "US West",
    type: "Staging",
    status: "Connected",
  },
  {
    id: "xm-dev",
    name: "XM Cloud Development",
    project: "North America Sites",
    region: "US East",
    type: "Development",
    status: "Connected",
  },
  {
    id: "xm-eu",
    name: "EU Content Hub",
    project: "European Sites",
    region: "EU Central",
    type: "Staging",
    status: "Needs attention",
  },
];

export const contentTree: ContentTreeItem[] = [
  {
    id: "home",
    name: "Home",
    path: "/sitecore/content/Content Bridge/Home",
    template: "Page",
    updatedAt: "2026-07-09 16:42",
    dependencies: ["layout-main", "datasource-hero"],
    children: [
      {
        id: "home-products",
        name: "Products",
        path: "/sitecore/content/Content Bridge/Home/Products",
        template: "Landing Page",
        updatedAt: "2026-07-08 12:20",
        dependencies: ["layout-main", "rendering-card-list"],
        children: [
          {
            id: "home-products-launchpad",
            name: "Launchpad",
            path: "/sitecore/content/Content Bridge/Home/Products/Launchpad",
            template: "Product Page",
            updatedAt: "2026-07-10 09:15",
            dependencies: ["media-launchpad", "datasource-pricing"],
          },
          {
            id: "home-products-atlas",
            name: "Atlas",
            path: "/sitecore/content/Content Bridge/Home/Products/Atlas",
            template: "Product Page",
            updatedAt: "2026-07-09 18:10",
            dependencies: ["media-atlas"],
          },
        ],
      },
      {
        id: "home-insights",
        name: "Insights",
        path: "/sitecore/content/Content Bridge/Home/Insights",
        template: "Listing Page",
        updatedAt: "2026-07-07 14:02",
        dependencies: ["layout-main", "rendering-article-list"],
      },
    ],
  },
  {
    id: "data",
    name: "Data",
    path: "/sitecore/content/Content Bridge/Data",
    template: "Folder",
    updatedAt: "2026-07-06 08:33",
    dependencies: [],
    children: [
      {
        id: "datasource-hero",
        name: "Hero datasource",
        path: "/sitecore/content/Content Bridge/Data/Hero datasource",
        template: "Hero",
        updatedAt: "2026-07-09 11:27",
        dependencies: ["media-hero"],
      },
      {
        id: "datasource-pricing",
        name: "Pricing datasource",
        path: "/sitecore/content/Content Bridge/Data/Pricing datasource",
        template: "Pricing Table",
        updatedAt: "2026-07-10 07:50",
        dependencies: [],
      },
    ],
  },
  {
    id: "media",
    name: "Media Library",
    path: "/sitecore/media library/Content Bridge",
    template: "Media Folder",
    updatedAt: "2026-07-05 15:11",
    dependencies: [],
    children: [
      {
        id: "media-hero",
        name: "Homepage hero",
        path: "/sitecore/media library/Content Bridge/Homepage hero",
        template: "Image",
        updatedAt: "2026-07-09 11:22",
        dependencies: [],
      },
      {
        id: "media-launchpad",
        name: "Launchpad gallery",
        path: "/sitecore/media library/Content Bridge/Launchpad gallery",
        template: "Image Folder",
        updatedAt: "2026-07-09 19:48",
        dependencies: [],
      },
    ],
  },
];

export const dependencyFindings: DependencyFinding[] = [
  {
    id: "dep-1",
    itemName: "Launchpad",
    dependency: "Pricing datasource",
    severity: "warning",
    message: "Referenced datasource is not selected. Include dependency or confirm destination already has it.",
  },
  {
    id: "dep-2",
    itemName: "Hero datasource",
    dependency: "Homepage hero",
    severity: "info",
    message: "Media item can be included in the transfer request.",
  },
  {
    id: "dep-3",
    itemName: "Products",
    dependency: "Card list rendering",
    severity: "critical",
    message: "Rendering definition is missing in destination validation snapshot.",
  },
];

const auditLog: AuditLogEntry[] = [
  {
    id: "audit-1",
    timestamp: "2026-07-10 10:12",
    actor: "Aditi Sharma",
    action: "Created transfer request",
    detail: "Content Transfer API request ct-98342 was created.",
  },
  {
    id: "audit-2",
    timestamp: "2026-07-10 10:13",
    actor: "Content Bridge",
    action: "Started item consumption",
    detail: "Item Transfer API started consuming blob bridge-prod-stage-0710.zip.",
  },
  {
    id: "audit-3",
    timestamp: "2026-07-10 10:22",
    actor: "Content Bridge",
    action: "Dependency validation",
    detail: "One warning was detected and accepted before promotion.",
  },
];

export const transfers: TransferRecord[] = [
  {
    id: "tr-1042",
    name: "Launchpad campaign refresh",
    sourceEnvironmentId: "xm-stage",
    destinationEnvironmentId: "xm-prod",
    selectedItemIds: ["home-products-launchpad", "datasource-pricing", "media-launchpad"],
    strategy: "merge",
    status: "transferring",
    progress: 68,
    createdBy: "Aditi Sharma",
    createdAt: "2026-07-10 10:12",
    updatedAt: "2026-07-10 10:25",
    contentTransferRequestId: "ct-98342",
    itemTransferJobId: "it-44190",
    blobUrl: "bridge-prod-stage-0710.zip",
    auditLog,
  },
  {
    id: "tr-1039",
    name: "Homepage hero update",
    sourceEnvironmentId: "xm-dev",
    destinationEnvironmentId: "xm-stage",
    selectedItemIds: ["datasource-hero", "media-hero"],
    strategy: "overwrite",
    status: "completed",
    progress: 100,
    createdBy: "Marcus Lee",
    createdAt: "2026-07-09 16:45",
    updatedAt: "2026-07-09 16:57",
    contentTransferRequestId: "ct-98288",
    itemTransferJobId: "it-44071",
    blobUrl: "bridge-dev-stage-0709.zip",
    auditLog,
  },
  {
    id: "tr-1035",
    name: "Product taxonomy alignment",
    sourceEnvironmentId: "xm-stage",
    destinationEnvironmentId: "xm-prod",
    selectedItemIds: ["home-products"],
    strategy: "skipExisting",
    status: "failed",
    progress: 42,
    createdBy: "Priya Menon",
    createdAt: "2026-07-08 14:30",
    updatedAt: "2026-07-08 14:46",
    contentTransferRequestId: "ct-98177",
    itemTransferJobId: "it-43980",
    blobUrl: "bridge-stage-prod-0708.zip",
    failureReason: "Destination validation rejected missing rendering definition.",
    auditLog,
  },
];
